# Copyright (C) 2021 Devin Lin <espidev@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
